### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Jacob Broms Engblom
email: jacob@likeneveralways.com
description: Portfolio of Jacob Broms Engblom
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#0000ff'
twitter_username: osfa
github_username:  osfa
instagram_username: jacobbromsengblom
author: Jacob Broms Engblom
logo: assets/images/share-image.png
twitter:
  username: osfa
social:
  name: Jacob Broms Engblom
  links:
    - https://twitter.com/osfa
    - https://www.instagram.com/jacobbromsengblom/
    - http://www.likeneveralways.com

languages: ["en"]
ampdir: amp
netlify_cms: true

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
google_analytics: G-56N146N9PN
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true
turbolinks:
  enabled: true # Set to false if you want to use the tag
  url: /turbolinks.js

### Build settings
markdown: kramdown
minify_html: false
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - jekyll-multiple-languages-plugin
  - amp-jekyll
  - jekyll-turbolinks

### Exclude from processing.
exclude:
  - Gemfile
  - .ruby-gemset
  - .ruby-version
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
